default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: check-added-large-files
    - id: check-yaml
      args: ["--unsafe"]
    - id: check-toml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: detect-private-key

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/adamchainz/blacken-docs
    rev: "1.18.0"  # replace with latest tag on GitHub
    hooks:
      - id: blacken-docs
        additional_dependencies:
        - black==22.12.0
        args: ["--line-length=80", "--target-version=py310"]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        args: ["--disable", "MD013"]
